import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../models/order.dart';
import '../localization/app_format.dart';

/// Builds a PDF invoice (buyer copy) or sales statement (farmer copy,
/// with the platform fee and net payout) for an order. Generated on the
/// device, so it works on the free plan and offline.
Future<Uint8List> buildInvoicePdf(FarmoraOrder o, {required bool farmerCopy}) async {
  final doc = pw.Document(title: 'Farmora ${o.displayNumber}');
  String lkr(int minor) => AppFormat.lkr(minor / 100, decimals: 2);
  final subtotal = o.subtotalMinor;
  final fee = o.deliveryFeeMinor;
  final total = o.totalMinor > 0 ? o.totalMinor : (o.totalAmountNumber * 100).round();
  final qty = o.items.isNotEmpty ? '${o.items.first['quantity'] ?? ''} ${o.unit}' : o.quantity;
  final unitPrice = o.items.isNotEmpty && o.items.first['pricePerUnitMinor'] is num
      ? lkr((o.items.first['pricePerUnitMinor'] as num).toInt())
      : o.unitPrice;

  pw.Widget row(String label, String value, {bool bold = false}) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 3),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(label),
            pw.Text(value,
                style: bold ? pw.TextStyle(fontWeight: pw.FontWeight.bold) : null),
          ],
        ),
      );

  doc.addPage(pw.Page(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.all(36),
    build: (_) => pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Farmora',
                style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#1B5E20'))),
            pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
              pw.Text(farmerCopy ? 'SALES STATEMENT' : 'INVOICE',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text(o.displayNumber),
              pw.Text(AppFormat.date(o.createdAt)),
            ]),
          ],
        ),
        pw.SizedBox(height: 24),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Expanded(
              child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                pw.Text('Seller (farmer)', style: const pw.TextStyle(color: PdfColors.grey700)),
                pw.Text(o.farmerName.isEmpty ? '-' : o.farmerName),
              ]),
            ),
            pw.Expanded(
              child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                pw.Text('Buyer', style: const pw.TextStyle(color: PdfColors.grey700)),
                pw.Text(o.buyerName.isEmpty ? '-' : o.buyerName),
                if (o.buyerCompany.isNotEmpty) pw.Text(o.buyerCompany),
                pw.Text(o.deliveryAddress),
              ]),
            ),
          ],
        ),
        pw.SizedBox(height: 24),
        pw.TableHelper.fromTextArray(
          headers: ['Item', 'Quantity', 'Unit price', 'Amount'],
          data: [
            [o.productName.isEmpty ? o.title : o.productName, qty, unitPrice, lkr(subtotal)],
          ],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
          headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#2E7D32')),
          cellAlignments: {1: pw.Alignment.center, 2: pw.Alignment.centerRight, 3: pw.Alignment.centerRight},
        ),
        pw.SizedBox(height: 16),
        pw.Container(
          alignment: pw.Alignment.centerRight,
          child: pw.SizedBox(
            width: 260,
            child: pw.Column(children: [
              row('Subtotal', lkr(subtotal)),
              row('Delivery', lkr(fee)),
              pw.Divider(),
              row('Total', lkr(total), bold: true),
              if (farmerCopy) ...[
                row('Platform fee', '- ${lkr(o.platformFeeMinor)}'),
                row('Net to farmer', lkr(subtotal - o.platformFeeMinor), bold: true),
              ],
            ]),
          ),
        ),
        pw.SizedBox(height: 24),
        pw.Text('Payment: ${o.paymentMethod.toUpperCase()} · ${o.paymentStatus}'),
        pw.Spacer(),
        pw.Text('Generated by the Farmora app. Amounts in LKR.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
      ],
    ),
  ));
  return doc.save();
}

/// Opens the platform share / print sheet for the order's PDF.
Future<void> shareInvoice(FarmoraOrder o, {required bool farmerCopy}) async {
  final bytes = await buildInvoicePdf(o, farmerCopy: farmerCopy);
  await Printing.sharePdf(
    bytes: bytes,
    filename: '${farmerCopy ? 'statement' : 'invoice'}-${o.displayNumber}.pdf',
  );
}
