// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate this file, run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyW98LURPAlM5jcT_bdETj-3Xq2Yw5Kg',
    appId: '1:33678627494:web:11924c52ff26413d549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    authDomain: 'farmingapp-24b34.firebaseapp.com',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    measurementId: 'G-29KHX2SH5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvO-upUbT-4-kaDHqP2j2CUpYT4j2_qs',
    appId: '1:33678627494:android:6d2db665cdbd33ff549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    iosBundleId: 'com.example.farmora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    iosBundleId: 'com.example.farmora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbyW98LURPAlM5jcT_bdETj-3Xq2Yw5Kg',
    appId: '1:33678627494:web:11924c52ff26413d549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    authDomain: 'farmingapp-24b34.firebaseapp.com',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    measurementId: 'G-29KHX2SH5H',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBbyW98LURPAlM5jcT_bdETj-3Xq2Yw5Kg',
    appId: '1:33678627494:web:11924c52ff26413d549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    authDomain: 'farmingapp-24b34.firebaseapp.com',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    measurementId: 'G-29KHX2SH5H',
  );
}
