// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate this file, run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDv8Pz6esu0UyNfi_S_g68sAD0gWLl7CQ',
    appId: '1:83367323369:web:d4ec7cdeab448652a83278',
    messagingSenderId: '83367323369',
    projectId: 'farmora-1da5a',
    authDomain: 'farmora-1da5a.firebaseapp.com',
    storageBucket: 'farmora-1da5a.firebasestorage.app',
    measurementId: 'G-V42N6Z61LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbeqlZ-Q18_fYWyFCEzKl9ZZgPNVBGl0',
    appId: '1:83367323369:android:56f5bdcfd2c40ccda83278',
    messagingSenderId: '83367323369',
    projectId: 'farmora-1da5a',
    storageBucket: 'farmora-1da5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = macos;

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhe--bzhfT9O3eD4HWUTIXXVBsjZSKi8I',
    appId: '1:83367323369:ios:0449923b8e488ce9a83278',
    messagingSenderId: '83367323369',
    projectId: 'farmora-1da5a',
    storageBucket: 'farmora-1da5a.firebasestorage.app',
    iosClientId: '83367323369-nccqd050c644g08dmh4uf1okp9bd3s7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmora',
  );

  static const FirebaseOptions windows = android;

  static const FirebaseOptions linux = android;
  
}
