// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate this file, run `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyW98LURPAlM5jcT_bdETj-3Xq2Yw5Kg',
    appId: '1:33678627494:web:11924c52ff26413d549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    authDomain: 'farmingapp-24b34.firebaseapp.com',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
    measurementId: 'G-29KHX2SH5H',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvO-upUbT-4-kaDHqP2j2CUpYT4j2_qs',
    appId: '1:33678627494:android:6d2db665cdbd33ff549a67',
    messagingSenderId: '33678627494',
    projectId: 'farmingapp-24b34',
    storageBucket: 'farmingapp-24b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = macos;

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhe--bzhfT9O3eD4HWUTIXXVBsjZSKi8I',
    appId: '1:83367323369:ios:0449923b8e488ce9a83278',
    messagingSenderId: '83367323369',
    projectId: 'farmora-1da5a',
    storageBucket: 'farmora-1da5a.firebasestorage.app',
    iosClientId: '83367323369-nccqd050c644g08dmh4uf1okp9bd3s7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmora',
  );

  static const FirebaseOptions windows = android;

  static const FirebaseOptions linux = android;
  
}
