import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(const FarmoraApp());

enum Role { farmer, buyer, transporter }
extension RoleInfo on Role { String get label => ["Farmer", "Buyer", "Transport provider"][index]; IconData get icon => [Icons.agriculture_rounded, Icons.shopping_basket_rounded, Icons.local_shipping_rounded][index]; }

class Product { final String name, category, location, quantity, price, emoji; final Color color; const Product(this.name,this.category,this.location,this.quantity,this.price,this.emoji,this.color); }
class FarmoraState extends ChangeNotifier { bool signedIn=false; String language="English"; Role role=Role.buyer; final products=<Product>[const Product('Organic Tomatoes','Vegetables','Nuwara Eliya','20 kg available','LKR 420 / kg','🍅',Color(0xffffe1da)),const Product('Cavendish Bananas','Fruits','Ambalantota','45 kg available','LKR 280 / kg','🍌',Color(0xfffff0c2)),const Product('Gotukola Bunches','Herbs','Kandy','80 bunches','LKR 90 / bunch','🌿',Color(0xffddf1dd))]; void signIn(Role r){role=r;signedIn=true;notifyListeners();} void setLanguage(String value){language=value;notifyListeners();} void signOut(){signedIn=false;notifyListeners();} void setRole(Role r){role=r;notifyListeners();} void add(Product p){products.insert(0,p);notifyListeners();} }

class FarmoraApp extends StatelessWidget { const FarmoraApp({super.key}); @override Widget build(BuildContext context)=>ChangeNotifierProvider(create:(_)=>FarmoraState(),child:MaterialApp(debugShowCheckedModeBanner:false,title:'Farmora',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff1f7a4d)),scaffoldBackgroundColor:const Color(0xfff7faf7),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(16)),borderSide:BorderSide.none))),home:const AuthGate())); }

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home>{int tab=0;@override Widget build(BuildContext context){final s=context.watch<FarmoraState>(), r=s.role;final screens=r==Role.transporter?[const Dashboard(),const Jobs(),const Orders(),const Profile()]:[const Dashboard(),const Products(),const Orders(),const Profile()];return Scaffold(body:SafeArea(child:IndexedStack(index:tab,children:screens)),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:(r==Role.transporter?['Overview','Jobs','Orders','Profile']:['Home','Products','Orders','Profile']).asMap().entries.map((e)=>NavigationDestination(icon:Icon([Icons.home_rounded,Icons.eco_rounded,Icons.receipt_long_rounded,Icons.person_rounded][e.key]),label:e.value)).toList()));}}

class Dashboard extends StatelessWidget { const Dashboard({super.key}); @override Widget build(BuildContext context){final s=context.watch<FarmoraState>(),r=s.role;final buyer=r==Role.buyer;return ListView(padding:const EdgeInsets.fromLTRB(20,16,20,24),children:[Row(children:[CircleAvatar(backgroundColor:const Color(0xffdcefe2),child:Icon(r.icon,color:const Color(0xff1f7a4d))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good morning',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Text('Your Farmora network is growing.',style:TextStyle(color:Colors.black54))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none_rounded))]),const SizedBox(height:24),if(buyer)const SearchBar(hintText:'Search fresh produce',leading:Icon(Icons.search_rounded)),if(buyer)const SizedBox(height:20),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xff1f7a4d),borderRadius:BorderRadius.circular(24)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(buyer?'Fresh produce,\nstraight to you.':r==Role.farmer?'Sell your harvest\nwith confidence.':'Earn while you\nserve your community.',style:const TextStyle(color:Colors.white,fontSize:23,fontWeight:FontWeight.w800)),const SizedBox(height:12),const Text('Support local farmers today.',style:TextStyle(color:Color(0xffd8f1df))),const SizedBox(height:16),FilledButton(onPressed:(){},style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:const Color(0xff1f7a4d)),child:Text(buyer?'Shop now':r==Role.farmer?'Add product':'Find jobs'))])),const Icon(Icons.eco_rounded,color:Color(0xffb9e5c5),size:80)]),const SizedBox(height:24),Text(buyer?'Explore categories':'Your overview',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:18)),const SizedBox(height:12),if(buyer)const Wrap(spacing:8,runSpacing:8,children:[Chip(avatar:Icon(Icons.grass,size:18),label:Text('Vegetables')),Chip(avatar:Icon(Icons.apple,size:18),label:Text('Fruits')),Chip(avatar:Icon(Icons.local_florist,size:18),label:Text('Herbs'))]),if(!buyer)Row(children:[Expanded(child:Stat('Active products',r==Role.farmer?'${s.products.length}':'8',Icons.insights_rounded)),const SizedBox(width:12),const Expanded(child:Stat('Pending orders','4',Icons.trending_up_rounded))]),const SizedBox(height:24),Text(buyer?'Picked for you':'Recent orders',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:18)),const SizedBox(height:12),if(buyer)...s.products.take(2).map((p)=>Tile(p)),if(!buyer)const OrderCard(title:'Organic Tomatoes',detail:'20 kg · Today',status:'In transit',color:Color(0xff3478c5)),const SizedBox(height:16),OutlinedButton.icon(onPressed:()=>showModalBottomSheet(context:context,builder:(_)=>const RoleSheet()),icon:const Icon(Icons.swap_horiz_rounded),label:const Text('Preview another role'))]);}}
class Stat extends StatelessWidget{final String l,v;final IconData i;const Stat(this.l,this.v,this.i,{super.key});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:const Color(0xff1f7a4d)),const SizedBox(height:10),Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Text(l,style:const TextStyle(color:Colors.black54))])));}

class Products extends StatelessWidget{const Products({super.key});@override Widget build(BuildContext c){final s=c.watch<FarmoraState>(),farmer=s.role==Role.farmer;return Scaffold(appBar:AppBar(title:Text(farmer?'My products':'Browse produce'),actions:[if(farmer)IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>const AddProduct()),icon:const Icon(Icons.add_rounded))]),body:ListView(padding:const EdgeInsets.all(20),children:[if(!farmer)const SearchBar(hintText:'Search by product or location',leading:Icon(Icons.search_rounded)),const SizedBox(height:16),...s.products.map((p)=>Tile(p,actions:farmer))]);}}
class Tile extends StatelessWidget{final Product p;final bool actions;const Tile(this.p,{super.key,this.actions=false});@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Container(width:76,height:76,alignment:Alignment.center,decoration:BoxDecoration(color:p.color,borderRadius:BorderRadius.circular(16)),child:Text(p.emoji,style:const TextStyle(fontSize:36))),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16)),Text('${p.category} · ${p.location}',style:const TextStyle(color:Colors.black54)),const SizedBox(height:7),Text(p.price,style:const TextStyle(color:Color(0xff1f7a4d),fontWeight:FontWeight.w800)),Text(p.quantity,style:const TextStyle(color:Colors.black54,fontSize:12))])),if(actions)const Icon(Icons.more_vert)])));}

class Orders extends StatelessWidget{const Orders({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Orders')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Track every step from farm to table.',style:TextStyle(color:Colors.black54)),const SizedBox(height:20),const OrderCard(title:'Organic Tomatoes',detail:'20 kg · LKR 8,400 · Today',status:'In transit',color:Color(0xff3478c5)),const OrderCard(title:'Cavendish Bananas',detail:'15 kg · LKR 4,200 · Yesterday',status:'Delivered',color:Color(0xff1f7a4d))]));}
class OrderCard extends StatelessWidget{final String title,detail,status;final Color color;const OrderCard({super.key,required this.title,required this.detail,required this.status,required this.color});@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))),Text(status,style:TextStyle(color:color,fontWeight:FontWeight.w700))]),const SizedBox(height:8),Text(detail,style:const TextStyle(color:Colors.black54)),const SizedBox(height:14),const LinearProgressIndicator(value:.68,minHeight:7,color:Color(0xff1f7a4d))])));}

class Jobs extends StatelessWidget{const Jobs({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Available jobs')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Choose a delivery that fits your route.',style:TextStyle(color:Colors.black54)),const SizedBox(height:20),const Job('Coconut harvest','Kaduwela → Colombo','250 kg · Pickup today, 10:30 AM','LKR 3,500'),const Job('Fresh vegetables','Nuwara Eliya → Kandy','80 kg · Pickup tomorrow, 7:00 AM','LKR 5,200')]);}}
class Job extends StatelessWidget{final String t,r,d,f;const Job(this.t,this.r,this.d,this.f,{super.key});@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.route_rounded,color:Color(0xff1f7a4d)),const SizedBox(width:8),Expanded(child:Text(t,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))),Text(f,style:const TextStyle(color:Color(0xff1f7a4d),fontWeight:FontWeight.w800))]),const SizedBox(height:12),Text(r,style:const TextStyle(fontWeight:FontWeight.w600)),Text(d,style:const TextStyle(color:Colors.black54)),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){},child:const Text('Accept job')))])));}
class Profile extends StatelessWidget{const Profile({super.key});@override Widget build(BuildContext c){final r=c.watch<FarmoraState>().role;return ListView(padding:const EdgeInsets.all(20),children:[Text('Profile',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:24),const CircleAvatar(radius:40,backgroundColor:Color(0xffdcefe2),child:Icon(Icons.person,size:42,color:Color(0xff1f7a4d))),const SizedBox(height:12),const Center(child:Text('Alex Perera',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800))),Center(child:Text(r.label,style:const TextStyle(color:Colors.black54))),const SizedBox(height:28),const ListTile(leading:Icon(Icons.language),title:Text('Language'),subtitle:Text(c.watch<FarmoraState>().language),trailing:Icon(Icons.chevron_right),onTap:()=>showModalBottomSheet(context:c,builder:(_)=>const LanguagePicker())),const ListTile(leading:Icon(Icons.help_outline),title:Text('Help & support'),trailing:Icon(Icons.chevron_right)),const ListTile(leading:Icon(Icons.settings_outlined),title:Text('Settings'),trailing:Icon(Icons.chevron_right)),ListTile(leading:const Icon(Icons.logout),title:const Text('Sign out'),onTap:()=>c.read<FarmoraState>().signOut())]);}}
class RoleSheet extends StatelessWidget{const RoleSheet({super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Switch preview role',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),...Role.values.map((r)=>ListTile(leading:Icon(r.icon),title:Text(r.label),onTap:(){c.read<FarmoraState>().setRole(r);Navigator.pop(c);} ))]));}
class AddProduct extends StatefulWidget{const AddProduct({super.key});@override State<AddProduct> createState()=>_AddProductState();}
class _AddProductState extends State<AddProduct>{final n=TextEditingController(),q=TextEditingController(),p=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Add a product'),content:SingleChildScrollView(child:Column(children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Product name')),const SizedBox(height:10),TextField(controller:q,decoration:const InputDecoration(labelText:'Quantity')),const SizedBox(height:10),TextField(controller:p,decoration:const InputDecoration(labelText:'Price per unit'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:(){if(n.text.isNotEmpty)c.read<FarmoraState>().add(Product(n.text,'Vegetables','Your farm','${q.text} available','LKR ${p.text} / unit','🥬',const Color(0xffddf1dd)));Navigator.pop(c);},child:const Text('Publish'))]);}
class AuthGate extends StatelessWidget{const AuthGate({super.key});@override Widget build(BuildContext c)=>c.watch<FarmoraState>().signedIn?const Home():const WelcomeScreen();}
class WelcomeScreen extends StatefulWidget{const WelcomeScreen({super.key});@override State<WelcomeScreen> createState()=>_WelcomeState();}
class _WelcomeState extends State<WelcomeScreen>{Role selected=Role.buyer;@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(24,48,24,32),children:[const Text('Welcome to\nFarmora',style:TextStyle(fontSize:40,height:1.05,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Text('A fairer, fresher way to connect farms, families, and reliable transport.',style:TextStyle(fontSize:17,color:Colors.black54,height:1.4)),const SizedBox(height:36),const Text('I am joining as a…',style:TextStyle(fontWeight:FontWeight.w800,fontSize:17)),const SizedBox(height:12),...Role.values.map((r)=>Padding(padding:const EdgeInsets.only(bottom:10),child:ListTile(onTap:()=>setState(()=>selected=r),leading:Icon(r.icon,color:const Color(0xff1f7a4d)),title:Text(r.label,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:Icon(selected==r?Icons.radio_button_checked:Icons.radio_button_off,color:const Color(0xff1f7a4d)),tileColor:selected==r?const Color(0xffe4f3e8):Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>c.read<FarmoraState>().signIn(selected),child:const Padding(padding:EdgeInsets.symmetric(vertical:5),child:Text('Continue to Farmora')))),const SizedBox(height:16),const Center(child:Text('Demo mode · No account required',style:TextStyle(color:Colors.black45,fontSize:12)))])));}}
class LanguagePicker extends StatelessWidget{const LanguagePicker({super.key});@override Widget build(BuildContext c)=>Column(mainAxisSize:MainAxisSize.min,children:['English','සිංහල','தமிழ்'].map((l)=>ListTile(title:Text(l),onTap:(){c.read<FarmoraState>().setLanguage(l);Navigator.pop(c);})).toList());}
