import 'package:flutter/material.dart';
import '../../models/product.dart';
import '../../models/order.dart';
import '../../models/transport_job.dart';
import '../../models/offer.dart';
import '../../models/market_price_index.dart';

/// Preloaded authentic catalog of Sri Lankan agricultural produce, harvest items,
/// orders, transport jobs, and market intelligence for the Farmora platform.
class DemoCatalogData {
  static List<Product> get sampleProducts => products;
  static List<FarmoraOrder> get sampleOrders => orders;
  static List<TransportJob> get sampleJobs => jobs;
  static List<FarmoraOffer> get sampleOffers => offers;
  static List<MarketPriceIndex> get sampleMarketPrices => marketPrices;

  static final List<Product> products = [
    Product(
      id: 'prod-1',
      name: 'Organic Red Tomatoes',
      category: 'Vegetables',
      location: 'Nuwara Eliya',
      quantity: '250 kg available',
      unit: 'kg',
      price: 'LKR 180.00 / kg',
      pricePerUnit: 180.0,
      priceMinor: 18000,
      quantityAvailable: 250,
      emoji: '🍅',
      color: const Color(0xFFFFEBEE),
      imagePath: 'assets/images/roma_tomatoes_1.png',
      images: const [
        'assets/images/roma_tomatoes_1.png',
        'assets/images/roma_tomatoes_2.png',
        'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Organic Certified',
      description:
          'Highland organic ripe Roma tomatoes harvested at peak freshness from Nuwara Eliya misty hills. High Brix sweetness and rich firm pulp.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 1)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-TOM-001',
    ),
    Product(
      id: 'prod-2',
      name: 'Fresh Mountain Carrots',
      category: 'Vegetables',
      location: 'Nuwara Eliya',
      quantity: '400 kg available',
      unit: 'kg',
      price: 'LKR 240.00 / kg',
      pricePerUnit: 240.0,
      priceMinor: 24000,
      quantityAvailable: 400,
      emoji: '🥕',
      color: const Color(0xFFFFF3E0),
      imagePath: 'assets/images/nantes_carrots.png',
      images: const [
        'assets/images/nantes_carrots.png',
        'https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Gold Supplier',
      description:
          'Crunchy sweet farm fresh mountain Nantes carrots, washed and graded directly from Nuwara Eliya terraces.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 2)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-CAR-002',
    ),
    Product(
      id: 'prod-3',
      name: 'Heirloom Salad Tomatoes',
      category: 'Vegetables',
      location: 'Kandy',
      quantity: '180 kg available',
      unit: 'kg',
      price: 'LKR 210.00 / kg',
      pricePerUnit: 210.0,
      priceMinor: 21000,
      quantityAvailable: 180,
      emoji: '🍅',
      color: const Color(0xFFFFEBEE),
      imagePath: 'assets/images/heirloom_tomatoes.png',
      images: const [
        'assets/images/heirloom_tomatoes.png',
        'https://images.unsplash.com/photo-1546470427-e26264be0b11?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1546470427-e26264be0b11?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Verified Farmer',
      description:
          'Rich multi-colored heirloom salad tomatoes grown in poly tunnels with organic bio-fertilizers. Ideal for salads and gourmet culinary use.',
      farmerId: 'farmer_demo_2',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 1)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-HEIR-003',
    ),
    Product(
      id: 'prod-4',
      name: 'Fresh Romaine Lettuce',
      category: 'Vegetables',
      location: 'Badulla',
      quantity: '120 kg available',
      unit: 'kg',
      price: 'LKR 320.00 / kg',
      pricePerUnit: 320.0,
      priceMinor: 32000,
      quantityAvailable: 120,
      emoji: '🥬',
      color: const Color(0xFFE8F5E9),
      imagePath: 'assets/images/romaine_lettuce.png',
      images: const [
        'assets/images/romaine_lettuce.png',
        'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Verified Farmer',
      description:
          'Crisp, fresh green romaine lettuce heads harvested pre-dawn to preserve maximum moisture, crispness, and vital nutrients.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now(),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-LET-004',
    ),
    Product(
      id: 'prod-5',
      name: 'Dinosaur Lacinato Kale',
      category: 'Herbs',
      location: 'Nuwara Eliya',
      quantity: '90 kg available',
      unit: 'kg',
      price: 'LKR 450.00 / kg',
      pricePerUnit: 450.0,
      priceMinor: 45000,
      quantityAvailable: 90,
      emoji: '🥬',
      color: const Color(0xFFE8F5E9),
      imagePath: 'assets/images/dinosaur_kale.png',
      images: const [
        'assets/images/dinosaur_kale.png',
        'https://images.unsplash.com/photo-1524179091875-bf99a9a6fa57?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1524179091875-bf99a9a6fa57?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Organic Certified',
      description:
          'Dark Tuscan Lacinato Kale, deeply wrinkled leaves packed with vitamins, iron, and rich antioxidants. Superfood quality from high altitudes.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.growing,
      harvestDate: DateTime.now().add(const Duration(days: 2)),
      availabilityDate: DateTime.now().add(const Duration(days: 2)),
      qrCode: 'FRM-QR-KALE-005',
    ),
    Product(
      id: 'prod-6',
      name: 'Black Beauty Eggplant',
      category: 'Vegetables',
      location: 'Dambulla',
      quantity: '300 kg available',
      unit: 'kg',
      price: 'LKR 190.00 / kg',
      pricePerUnit: 190.0,
      priceMinor: 19000,
      quantityAvailable: 300,
      emoji: '🍆',
      color: const Color(0xFFEDE7F6),
      imagePath: 'assets/images/black_beauty_eggplant.png',
      images: const [
        'assets/images/black_beauty_eggplant.png',
        'https://images.unsplash.com/photo-1615484477778-ca3b783256fd?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1615484477778-ca3b783256fd?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: false,
      trustLevel: 'Verified Farmer',
      description:
          'Glossy purple, tender eggplant harvested fresh from Dambulla agricultural fields. Smooth texture with small seeds.',
      farmerId: 'farmer_demo_2',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 1)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-EGG-006',
    ),
    Product(
      id: 'prod-7',
      name: 'Cavendish Golden Bananas',
      category: 'Fruits',
      location: 'Embilipitiya',
      quantity: '500 kg available',
      unit: 'kg',
      price: 'LKR 160.00 / kg',
      pricePerUnit: 160.0,
      priceMinor: 16000,
      quantityAvailable: 500,
      emoji: '🍌',
      color: const Color(0xFFFFFDE7),
      imagePath:
          'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Verified Farmer',
      description:
          'Naturally ripened sweet Cavendish bananas from Embilipitiya river valley groves. Free from chemical ripening agents.',
      farmerId: 'farmer_demo_3',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 1)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-BAN-007',
    ),
    Product(
      id: 'prod-8',
      name: 'Spicy Ceylon Green Chillies',
      category: 'Vegetables',
      location: 'Dambulla',
      quantity: '150 kg available',
      unit: 'kg',
      price: 'LKR 420.00 / kg',
      pricePerUnit: 420.0,
      priceMinor: 42000,
      quantityAvailable: 150,
      emoji: '🌶️',
      color: const Color(0xFFE8F5E9),
      imagePath:
          'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: false,
      trustLevel: 'Verified Farmer',
      description:
          'Fiery, pungent fresh green chillies direct from Dambulla agricultural belt. Hand-picked early morning for premium crispness.',
      farmerId: 'farmer_demo_2',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now(),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-CHIL-008',
    ),
    Product(
      id: 'prod-9',
      name: 'Alba Ceylon Cinnamon Sticks',
      category: 'Spices',
      location: 'Matale',
      quantity: '60 kg available',
      unit: 'kg',
      price: 'LKR 950.00 / kg',
      pricePerUnit: 950.0,
      priceMinor: 95000,
      quantityAvailable: 60,
      emoji: '🪵',
      color: const Color(0xFFEFEBE9),
      imagePath:
          'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Gold Supplier',
      description:
          'Pure export-grade Alba Ceylon cinnamon quills with exquisite aroma and sweet taste. Certified pure Cinnamomum verum.',
      farmerId: 'farmer_demo_2',
      harvestStatus: HarvestStatus.packed,
      harvestDate: DateTime.now().subtract(const Duration(days: 5)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-CIN-009',
    ),
    Product(
      id: 'prod-10',
      name: 'Red Dambulla Big Onions',
      category: 'Vegetables',
      location: 'Dambulla',
      quantity: '800 kg available',
      unit: 'kg',
      price: 'LKR 290.00 / kg',
      pricePerUnit: 290.0,
      priceMinor: 29000,
      quantityAvailable: 800,
      emoji: '🧅',
      color: const Color(0xFFFFEBEE),
      imagePath:
          'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: false,
      trustLevel: 'Verified Farmer',
      description:
          'Dry cured, long shelf-life red big onions harvested in dry-zone sunshine. Excellent for storage and culinary cooking.',
      farmerId: 'farmer_demo_3',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 3)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-ONI-010',
    ),
    Product(
      id: 'prod-11',
      name: 'Fresh Highland Potatoes',
      category: 'Vegetables',
      location: 'Welimada',
      quantity: '600 kg available',
      unit: 'kg',
      price: 'LKR 260.00 / kg',
      pricePerUnit: 260.0,
      priceMinor: 26000,
      quantityAvailable: 600,
      emoji: '🥔',
      color: const Color(0xFFFFF8E1),
      imagePath:
          'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: false,
      trustLevel: 'Verified Farmer',
      description:
          'Firm yellow-flesh Welimada potatoes ideal for cooking, curries, and roasting. Grown in nutrient-rich mountain soil.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 2)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-POT-011',
    ),
    Product(
      id: 'prod-12',
      name: 'Samba White Paddy Rice',
      category: 'Grains',
      location: 'Polonnaruwa',
      quantity: '1200 kg available',
      unit: 'kg',
      price: 'LKR 220.00 / kg',
      pricePerUnit: 220.0,
      priceMinor: 22000,
      quantityAvailable: 1200,
      emoji: '🌾',
      color: const Color(0xFFFFFDE7),
      imagePath:
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Gold Supplier',
      description:
          'Traditional fragrant Ceylon Samba rice from the ancient reservoir-irrigated paddy plains of Polonnaruwa. Milled fresh.',
      farmerId: 'farmer_demo_3',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 4)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-RIC-012',
    ),
    Product(
      id: 'prod-13',
      name: 'Sweet Karthacolomban Mangoes',
      category: 'Fruits',
      location: 'Jaffna',
      quantity: '350 kg available',
      unit: 'kg',
      price: 'LKR 380.00 / kg',
      pricePerUnit: 380.0,
      priceMinor: 38000,
      quantityAvailable: 350,
      emoji: '🥭',
      color: const Color(0xFFFFF3E0),
      imagePath:
          'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Verified Farmer',
      description:
          'Famous Jaffna Karthacolomban tree-ripened mangoes with succulent fiber-less sweet golden flesh and aromatic bouquet.',
      farmerId: 'farmer_demo_2',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now().subtract(const Duration(days: 1)),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-MAN-013',
    ),
    Product(
      id: 'prod-14',
      name: 'Fresh Gotukola & Ceylon Mint',
      category: 'Herbs',
      location: 'Gampaha',
      quantity: '80 kg available',
      unit: 'kg',
      price: 'LKR 120.00 / kg',
      pricePerUnit: 120.0,
      priceMinor: 12000,
      quantityAvailable: 80,
      emoji: '🌿',
      color: const Color(0xFFE8F5E9),
      imagePath:
          'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&auto=format&fit=crop&q=80',
      images: const [
        'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&auto=format&fit=crop&q=80',
      ],
      imageUrls: const [
        'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&auto=format&fit=crop&q=80',
      ],
      status: 'Active',
      isOrganic: true,
      trustLevel: 'Organic Certified',
      description:
          'High-vitality organic Gotukola (Centella asiatica) and wild Ceylon mint bunches for herbal teas, sambols, and salads.',
      farmerId: 'farmer_demo_1',
      harvestStatus: HarvestStatus.harvested,
      harvestDate: DateTime.now(),
      availabilityDate: DateTime.now(),
      qrCode: 'FRM-QR-GOT-014',
    ),
  ];

  static final List<FarmoraOrder> orders = [
    FarmoraOrder(
      id: 'ORD-1001',
      orderNumber: 'ORD-1001',
      title: 'Organic Red Tomatoes',
      productName: 'Organic Red Tomatoes',
      productId: 'prod-1',
      quantity: '25 kg',
      totalAmount: 'LKR 4,850.00',
      totalAmountNumber: 4850.0,
      buyerName: 'Cargills FoodCity',
      buyerCompany: 'Cargills Retail',
      deliveryAddress: 'No. 40, Colombo Road, Colombo 03',
      detail: 'Highland organic tomatoes batch A',
      status: 'In transit',
      progress: 0.7,
      color: const Color(0xFFE53935),
      timestamp: 'Today, 10:30 AM',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
      transporterId: 'trans_demo_1',
      subtotalMinor: 450000,
      deliveryFeeMinor: 35000,
      totalMinor: 485000,
      paymentStatus: 'Paid (Escrow)',
      escrowStatus: 'Held',
    ),
    FarmoraOrder(
      id: 'ORD-1002',
      orderNumber: 'ORD-1002',
      title: 'Fresh Mountain Carrots',
      productName: 'Fresh Mountain Carrots',
      productId: 'prod-2',
      quantity: '50 kg',
      totalAmount: 'LKR 12,350.00',
      totalAmountNumber: 12350.0,
      buyerName: 'Keells Super',
      buyerCompany: 'Keells Holdings',
      deliveryAddress: 'No. 12, Kandy Road, Kadawatha',
      detail: 'A-grade fresh mountain carrots',
      status: 'Accepted',
      progress: 0.4,
      color: const Color(0xFFFB8C00),
      timestamp: 'Yesterday',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
      transporterId: 'trans_demo_1',
      subtotalMinor: 1200000,
      deliveryFeeMinor: 35000,
      totalMinor: 1235000,
      paymentStatus: 'Payment Required',
      escrowStatus: 'Pending',
    ),
    FarmoraOrder(
      id: 'ORD-1003',
      orderNumber: 'ORD-1003',
      title: 'Alba Ceylon Cinnamon Sticks',
      productName: 'Alba Ceylon Cinnamon Sticks',
      productId: 'prod-9',
      quantity: '10 kg',
      totalAmount: 'LKR 9,850.00',
      totalAmountNumber: 9850.0,
      buyerName: 'Spices Lanka Ltd',
      buyerCompany: 'Spices Lanka',
      deliveryAddress: 'Export Processing Zone, Katunayake',
      detail: 'Alba grade certified cinnamon export batch',
      status: 'Delivered',
      progress: 1.0,
      color: const Color(0xFF43A047),
      timestamp: 'Sep 24, 2026',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_2',
      transporterId: 'trans_demo_2',
      subtotalMinor: 950000,
      deliveryFeeMinor: 35000,
      totalMinor: 985000,
      paymentStatus: 'Released',
      escrowStatus: 'Released',
    ),
    FarmoraOrder(
      id: 'ORD-1004',
      orderNumber: 'ORD-1004',
      title: 'Cavendish Golden Bananas',
      productName: 'Cavendish Golden Bananas',
      productId: 'prod-7',
      quantity: '40 kg',
      totalAmount: 'LKR 6,750.00',
      totalAmountNumber: 6750.0,
      buyerName: 'Green Supermarket',
      buyerCompany: 'Green Lanka Agro',
      deliveryAddress: 'Pettah Wholesale Market, Colombo 11',
      detail: 'Ripe Cavendish banana bunches',
      status: 'Pending',
      progress: 0.2,
      color: const Color(0xFFFDD835),
      timestamp: '2 hours ago',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_3',
      transporterId: '',
      subtotalMinor: 640000,
      deliveryFeeMinor: 35000,
      totalMinor: 675000,
      paymentStatus: 'Payment Required',
      escrowStatus: 'Pending',
    ),
  ];

  static final List<TransportJob> jobs = [
    const TransportJob(
      id: 'JOB-201',
      orderId: 'ORD-1001',
      title: 'Organic Tomatoes Delivery',
      route: 'Nuwara Eliya → Colombo 03',
      detail: '25 kg fresh produce in protective plastic crates',
      fee: 'LKR 1,500.00',
      status: 'inTransit',
      accepted: true,
      pickup: 'Nuwara Eliya Farm Gate',
      dropoff: 'Colombo 03 Distribution Centre',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
    ),
    const TransportJob(
      id: 'JOB-202',
      orderId: 'ORD-1002',
      title: 'Mountain Carrots Dispatch',
      route: 'Nuwara Eliya → Kadawatha',
      detail: '50 kg mountain carrots in ventilated jute bags',
      fee: 'LKR 2,200.00',
      status: 'requested',
      accepted: false,
      pickup: 'Nuwara Eliya High Street',
      dropoff: 'Keells Logistics Hub, Kadawatha',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
    ),
    const TransportJob(
      id: 'JOB-203',
      orderId: 'ORD-1003',
      title: 'Ceylon Cinnamon Export Transfer',
      route: 'Matale → Katunayake',
      detail: '10 kg Alba quills in sealed moisture-proof cartons',
      fee: 'LKR 3,500.00',
      status: 'delivered',
      accepted: true,
      pickup: 'Matale Spice Processing Unit',
      dropoff: 'Export Processing Zone, Katunayake',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_2',
    ),
    const TransportJob(
      id: 'JOB-204',
      orderId: 'ORD-1004',
      title: 'Bananas Bulk Freight',
      route: 'Embilipitiya → Pettah',
      detail: '40 kg naturally ripened Cavendish banana crates',
      fee: 'LKR 2,800.00',
      status: 'requested',
      accepted: false,
      pickup: 'Embilipitiya River Road',
      dropoff: 'Pettah Wholesale Yard, Colombo 11',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_3',
    ),
  ];

  static final List<FarmoraOffer> offers = [
    FarmoraOffer(
      id: 'OFFER-301',
      productId: 'prod-1',
      productName: 'Organic Red Tomatoes',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
      proposedQuantity: 80,
      proposedPrice: 165.0,
      status: 'pending',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    FarmoraOffer(
      id: 'OFFER-302',
      productId: 'prod-2',
      productName: 'Fresh Mountain Carrots',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_1',
      proposedQuantity: 120,
      proposedPrice: 220.0,
      status: 'countered',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    FarmoraOffer(
      id: 'OFFER-303',
      productId: 'prod-9',
      productName: 'Alba Ceylon Cinnamon Sticks',
      buyerId: 'buyer_demo',
      farmerId: 'farmer_demo_2',
      proposedQuantity: 15,
      proposedPrice: 900.0,
      status: 'accepted',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];

  static final List<MarketPriceIndex> marketPrices = [
    MarketPriceIndex(
      id: 'mpi-1',
      cropName: 'Organic Red Tomatoes',
      category: 'Vegetables',
      district: 'Dambulla',
      marketName: 'Dambulla Dedicated Economic Centre',
      minPricePerKg: 160.0,
      maxPricePerKg: 210.0,
      averagePricePerKg: 185.0,
      trend: 'up',
      updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    MarketPriceIndex(
      id: 'mpi-2',
      cropName: 'Fresh Mountain Carrots',
      category: 'Vegetables',
      district: 'Nuwara Eliya',
      marketName: 'Nuwara Eliya Pola',
      minPricePerKg: 220.0,
      maxPricePerKg: 270.0,
      averagePricePerKg: 245.0,
      trend: 'stable',
      updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    MarketPriceIndex(
      id: 'mpi-3',
      cropName: 'Alba Ceylon Cinnamon Sticks',
      category: 'Spices',
      district: 'Matale',
      marketName: 'Matale Spice Exchange',
      minPricePerKg: 900.0,
      maxPricePerKg: 1150.0,
      averagePricePerKg: 1025.0,
      trend: 'up',
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    MarketPriceIndex(
      id: 'mpi-4',
      cropName: 'Spicy Green Chillies',
      category: 'Vegetables',
      district: 'Pettah',
      marketName: 'Pettah Manning Market',
      minPricePerKg: 390.0,
      maxPricePerKg: 460.0,
      averagePricePerKg: 425.0,
      trend: 'down',
      updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    MarketPriceIndex(
      id: 'mpi-5',
      cropName: 'Red Dambulla Big Onions',
      category: 'Vegetables',
      district: 'Dambulla',
      marketName: 'Dambulla Dedicated Economic Centre',
      minPricePerKg: 270.0,
      maxPricePerKg: 320.0,
      averagePricePerKg: 295.0,
      trend: 'stable',
      updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    MarketPriceIndex(
      id: 'mpi-6',
      cropName: 'Cavendish Golden Bananas',
      category: 'Fruits',
      district: 'Embilipitiya',
      marketName: 'Embilipitiya Fruit Market',
      minPricePerKg: 140.0,
      maxPricePerKg: 180.0,
      averagePricePerKg: 160.0,
      trend: 'up',
      updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    MarketPriceIndex(
      id: 'mpi-7',
      cropName: 'Samba White Paddy Rice',
      category: 'Grains',
      district: 'Polonnaruwa',
      marketName: 'Polonnaruwa Paddy Board',
      minPricePerKg: 200.0,
      maxPricePerKg: 240.0,
      averagePricePerKg: 220.0,
      trend: 'stable',
      updatedAt: DateTime.now().subtract(const Duration(hours: 7)),
    ),
    MarketPriceIndex(
      id: 'mpi-8',
      cropName: 'Sweet Karthacolomban Mangoes',
      category: 'Fruits',
      district: 'Jaffna',
      marketName: 'Jaffna Central Market',
      minPricePerKg: 350.0,
      maxPricePerKg: 420.0,
      averagePricePerKg: 385.0,
      trend: 'up',
      updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
  ];

  /// Preset produce items that farmers can quickly pick from when adding a new crop
  static final List<Map<String, String>> presetProduceItems = [
    {
      'name': 'Organic Red Tomatoes',
      'category': 'Vegetables',
      'emoji': '🍅',
      'imagePath': 'assets/images/roma_tomatoes_1.png',
      'defaultPrice': '180',
      'unit': 'kg',
    },
    {
      'name': 'Fresh Mountain Carrots',
      'category': 'Vegetables',
      'emoji': '🥕',
      'imagePath': 'assets/images/nantes_carrots.png',
      'defaultPrice': '240',
      'unit': 'kg',
    },
    {
      'name': 'Heirloom Salad Tomatoes',
      'category': 'Vegetables',
      'emoji': '🍅',
      'imagePath': 'assets/images/heirloom_tomatoes.png',
      'defaultPrice': '210',
      'unit': 'kg',
    },
    {
      'name': 'Fresh Romaine Lettuce',
      'category': 'Vegetables',
      'emoji': '🥬',
      'imagePath': 'assets/images/romaine_lettuce.png',
      'defaultPrice': '320',
      'unit': 'kg',
    },
    {
      'name': 'Dinosaur Lacinato Kale',
      'category': 'Herbs',
      'emoji': '🥬',
      'imagePath': 'assets/images/dinosaur_kale.png',
      'defaultPrice': '450',
      'unit': 'kg',
    },
    {
      'name': 'Black Beauty Eggplant',
      'category': 'Vegetables',
      'emoji': '🍆',
      'imagePath': 'assets/images/black_beauty_eggplant.png',
      'defaultPrice': '190',
      'unit': 'kg',
    },
    {
      'name': 'Cavendish Golden Bananas',
      'category': 'Fruits',
      'emoji': '🍌',
      'imagePath':
          'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '160',
      'unit': 'kg',
    },
    {
      'name': 'Spicy Ceylon Green Chillies',
      'category': 'Vegetables',
      'emoji': '🌶️',
      'imagePath':
          'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '420',
      'unit': 'kg',
    },
    {
      'name': 'Alba Ceylon Cinnamon Sticks',
      'category': 'Spices',
      'emoji': '🪵',
      'imagePath':
          'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '950',
      'unit': 'kg',
    },
    {
      'name': 'Red Dambulla Big Onions',
      'category': 'Vegetables',
      'emoji': '🧅',
      'imagePath':
          'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '290',
      'unit': 'kg',
    },
    {
      'name': 'Fresh Highland Potatoes',
      'category': 'Vegetables',
      'emoji': '🥔',
      'imagePath':
          'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '260',
      'unit': 'kg',
    },
    {
      'name': 'Samba White Paddy Rice',
      'category': 'Grains',
      'emoji': '🌾',
      'imagePath':
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '220',
      'unit': 'kg',
    },
    {
      'name': 'Sweet Karthacolomban Mangoes',
      'category': 'Fruits',
      'emoji': '🥭',
      'imagePath':
          'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '380',
      'unit': 'kg',
    },
    {
      'name': 'Fresh Gotukola & Ceylon Mint',
      'category': 'Herbs',
      'emoji': '🌿',
      'imagePath':
          'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&auto=format&fit=crop&q=80',
      'defaultPrice': '120',
      'unit': 'kg',
    },
  ];
}
